name: CI with OpenID Connect

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  BUILD_DIR: build
  AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
  INDEX_DOCUMENT: index.html
  ERROR_DOCUMENT: 404.html

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          #cache: npm
          #cache-dependency-path: web/package-lock.json
          cache: "none"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: CI=false npm run build

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob service-properties update \
            --account-name "$AZURE_STORAGE_ACCOUNT" \
            --static-website \
            --index-document "$INDEX_DOCUMENT" \
            --404-document "$ERROR_DOCUMENT"
            --auth-mode key -d '$web' -s .

      # Azure logout
      #- name: logout
      #  run: |
      #   az logout
      # if: always()
